---
title: "Example 2: Computing Effect Sizes for Noninvariance With Multiple Grouping Variables"
date: last-modified
bibliography: ../manuscript/references.yaml
format: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(dplyr)
library(modelsummary)
library(lavaan)
# remotes::install_github("marklhc/pinsearch", ref = "contrast")
library(pinsearch)
```

## Load Data

```{r}
orig_dat <- haven::read_sav(
    here::here("LUI2018_class4mplus.sav")
)
dat <- orig_dat |>
    filter(eth %in% c(1, 2, 4), gender %in% 1:2) |>
    mutate( # across(class1:class15, .fns = as.numeric),
        across(c(eth, gender), .fns = as_factor),
        group = interaction(eth, gender)
    ) |>
    arrange(group)
# dat[,9:23] <- sapply(dat %>% select("class1":"class15"), FUN = function(x) ifelse(x > 3, 4, x))
# head(dat)
```

## Descriptive Statistics

```{r}
dat[-8] |>
    datasummary(
        formula = (class1 + class2 + class3 + class4 + class5 +
            class6 + class7 + class8 + class9 + class10 +
            class11 + class12 + class13 + class14 + class15) ~
            eth * gender *
            (N + Mean + SD)
    )
```

## Specification search

### Configural invariance

```{r}
config_mod <- "
f1 =~ class1 + class2 + class3 + class4 + class5 + class6 + 
      class7 + class8 + class9 + class10 + class11 + class12 + 
      class13 + class14 + class15
"
config_fit <- cfa(config_mod, data = dat, group = "group", estimator = "MLR",
                  missing = "fiml")
# Release covariance between class1 and class2
config_fit2 <- update(config_fit, c(config_mod, "class1 ~~ class2"))
anova(config_fit, config_fit2)
```

```{r}
#| include: false
config_path <- here::here("ex2_config.rds")
if (!file.exists(config_path)) {
    saveRDS(config_fit2, config_path)
}
```

Forward search [similar to @yoon2007]

```{r}
#| echo: true
#| eval: false
ps <- pinSearch(paste0(config_mod, "\nclass1 ~~ class2"), data = dat,
                group = "group", estimator = "MLR", missing = "fiml",
                type = "residual.covariances")
```

```{r}
#| include: false
ps_path <- here::here("ex2_ps.rds")
if (!file.exists(ps_path)) {
    ps <- pinSearch(paste0(config_mod, "\nclass1 ~~ class2"), data = dat,
                group = "group", estimator = "MLR", missing = "fiml",
                type = "residual.covariances",
                progress = TRUE, inv_test = "lrt", control_fdr = TRUE)
    saveRDS(ps, ps_path)
} else {
    ps <- readRDS(ps_path)
}
```

```{r}
knitr::kable(ps[[2]])
```

Parameter Estiamtes

Group labels:

```{r}
lavInspect(ps[[1]], what = "group.label")
```

```{r}
lavInspect(ps[[1]], what = "est") |>
    lapply(FUN = `[[`, "lambda") |>
    do.call(what = cbind) |>
    knitr::kable(digits = 3, caption = "Loading Estimates",
                 col.names = paste0("G", 1:6))
```

```{r}
lavInspect(ps[[1]], what = "est") |>
    lapply(FUN = `[[`, "nu") |>
    do.call(what = cbind) |>
    knitr::kable(digits = 3, caption = "Intercept Estimates",
                 col.names = paste0("G", 1:6))
```

```{r}
lavInspect(ps[[1]], what = "est") |>
    lapply(FUN = `[[`, "theta") |>
    lapply(FUN = diag) |>
    do.call(what = cbind) |>
    knitr::kable(digits = 3, caption = "Uniqueness Estimates",
                 col.names = paste0("G", 1:6))
```

## Effect Size

```{r}
# Obtain fmacs effect size
(f_omni <- pin_effsize(ps[[1]]))
# fmacs by gender
(f_gender <- pin_effsize(ps[[1]], group_factor = c(1, 1, 1, 2, 2, 2)))
# fmacs by ethnicity
(f_eth <- pin_effsize(ps[[1]], group_factor = c(1, 2, 3, 1, 2, 3)))
# interaction (using contrast matrix)
contr <- local({
    gen <- factor(c("F", "M"))
    contrasts(gen) <- contr.sum(length(gen))
    eth <- factor(1:3)
    contrasts(eth) <- contr.sum(length(eth))
    model.matrix(~ gen * eth, data = expand.grid(eth = eth, gen = gen))
})
(f_int <- pin_effsize(ps[[1]], contrast = contr[, 5:6, drop = FALSE]))
```

Bootstrapping

```{r}
fmacs_est <- c(f_omni, f_gender, f_eth, f_int)
```

```{r}
#| echo: true
#| eval: !expr '!file.exists("ex2_ps_boot.rds")'
ps_refit <- lavaan(parTable(ps[[1]]),
    data = dat, group = "group", estimator = "MLR",
    missing = "fiml"
)
ps_boot <- bootstrapLavaan(ps_refit,
    R = 200,
    FUN = \(x) c(
        pin_effsize(x),
        pin_effsize(x, group_factor = c(1, 1, 1, 2, 2, 2)),
        pin_effsize(x, group_factor = c(1, 2, 3, 1, 2, 3)),
        pin_effsize(x, contrast = contr[, 5:6, drop = FALSE])
    )
)
saveRDS(ps_boot, here::here("ex2_ps_boot.rds"))
```

```{r}
#| include: false
ps_boot <- readRDS(here::here("ex2_ps_boot.rds"))
```

```{r}
fmacs_boot <- structure(list(
    t0 = fmacs_est,
    t = ps_boot,
    R = 200, class = "boot"
))
# Bias
fmacs_bias <- colMeans(fmacs_boot$t, na.rm = TRUE) - fmacs_est
# Bias corrected fMACS
fmacs_est_bc <- pmax(0, fmacs_est - fmacs_bias)
# 95% Percentile CI
# Loop over indices
fmacs_boot_ci <- lapply(seq_len(ncol(fmacs_boot$t)), \(x) {
    boot_ci <- boot::boot.ci(
        fmacs_boot,
        type = c("norm", "basic", "perc"), index = x
    )
    list(
        norm = boot_ci$norm[2:3],
        basic = boot_ci$basic[4:5], perc = boot_ci$perc[4:5]
    )
})
```

```{r}
#| label: tbl-fmacs-ex2
f_omni_ci <- vapply(fmacs_boot_ci[1:8],
    FUN = \(x) paste0(
        "[", round(x$perc[1], 2), ", ",
        round(x$perc[2], 2), "]"
    ),
    FUN.VALUE = character(1)
)
f_gender_ci <- vapply(fmacs_boot_ci[9:16],
    FUN = \(x) paste0(
        "[", round(x$perc[1], 2), ", ",
        round(x$perc[2], 2), "]"
    ),
    FUN.VALUE = character(1)
)
f_eth_ci <- vapply(fmacs_boot_ci[17:24],
    FUN = \(x) paste0(
        "[", round(x$perc[1], 2), ", ",
        round(x$perc[2], 2), "]"
    ),
    FUN.VALUE = character(1)
)
f_int_ci <- vapply(fmacs_boot_ci[25:32],
    FUN = \(x) paste0(
        "[", round(x$perc[1], 2), ", ",
        round(x$perc[2], 2), "]"
    ),
    FUN.VALUE = character(1)
)
# Helper for formatting numbers
# Render as table
item_names <- gsub("class", replacement = "Item ", colnames(f_omni)) |>
    gsub(pattern = "-f1", replacement = "")
t(rbind(f_omni, f_gender, f_eth, f_int)) |>
    as.data.frame() |>
    `dimnames<-`(list(
        item_names,
        c("Overall", "Gender", "Ethnicity", "Gender x Ethnicity")
    )) |>
    knitr::kable(digits = 2, caption = "$f_\\text{MACS}$ effect sizes")
```

### Test-level effect sizes

```{r}
pin_effsize(ps[[1]], item_weights = rep(1, 15))
```

```{r}
#| echo: true
#| eval: !expr '!file.exists("ex2_pstest_boot.rds")'
# Bootstrap
pstest_boot <- bootstrapLavaan(ps_refit,
    R = 200,
    FUN = \(x) c(
        pin_effsize(x, item_weights = rep(1, 15))
    )
)
saveRDS(pstest_boot, here::here("ex2_pstest_boot.rds"))
```

```{r}
#| include: false
pstest_boot <- readRDS(here::here("ex2_pstest_boot.rds"))
```

```{r}
fmacstest_est <- pin_effsize(ps[[1]], item_weights = rep(1, 15))
fmacstest_boot <- structure(list(
    t0 = fmacstest_est,
    t = pstest_boot,
    R = 200, class = "boot"
))
# Bias
fmacstest_bias <- colMeans(fmacstest_boot$t, na.rm = TRUE) - fmacstest_est
# Bias corrected fMACS
fmacstest_est_bc <- pmax(0, fmacstest_est - fmacstest_bias)
# 95% Percentile CI
boot::boot.ci(
        fmacstest_boot,
        type = c("norm", "basic", "perc")
    )
```
