---
title: "Illustrative Example (Lui., 2019) with Categorical Data"
date: "2024-03-12"
format: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lavaan)
# remotes::install_github("marklhc/pinsearch", ref = "contrast")
library(pinsearch)
```

This is the same example as [ex2.qmd](ex2.qmd), but with the items treated as categorical. Only ethnicity is included as the grouping variable.

## Load Data

```{r}
orig_dat <- haven::read_sav(
    here::here("analysis", "LUI2018_class4mplus.sav")
)
dat <- orig_dat |>
    filter(eth %in% c(1, 2, 4)) |>
    mutate(eth = as_factor(eth)) |>
    arrange(eth)
```

## Specification search

### Configural invariance

```{r}
config_mod <- "
f1 =~ class1 + class2 + class3 + class4 + class5 + class6 + 
      class7 + class8 + class9 + class10 + class11 + class12 + 
      class13 + class14 + class15
"
config_fit <- cfa(config_mod, data = dat, group = "eth",
                  ordered = TRUE)
# Release covariance between class1 and class2
config_fit2 <- update(config_fit, c(config_mod, "class1 ~~ class2"))
anova(config_fit, config_fit2)
```

Forward search and effect size

```{r}
#| echo: true
#| cache: true
pinSearch(paste0(config_mod, "\nclass1 ~~ class2"),
    data = dat,
    group = "eth", ordered = TRUE,
    type = "residual.covariances",
    effect_size = TRUE
)
```
